language: groovy

jdk: oraclejdk8

install:
  - git clone https://github.com/mikessh/vdjtools.git
  - cd vdjtools/
  - git checkout tags/1.0.9
  - mvn clean install -q
  - cd ..

script:
  - gradle clean install
  - java -Xmx4G -jar `ls build/libs/vdjdb-*.jar` -v -j -S human -R TRB --search-scope 3,1,1,3 --search-preset high-precision src/test/resources/sergey_anatolyevich.gz test
  - if [[ ! -s test.sergey_anatolyevich.annot.txt ]]; then exit 1; fi
  - if [[ ! -s test.annot.summary.txt ]]; then exit 1; fi
  - rm test.sergey_anatolyevich.annot.txt
  - rm test.annot.summary.txt
  - java -Xmx4G -jar `ls build/libs/vdjdb-*.jar` --use-fat-db -v -j -S human -R TRB --search-scope 3,1,1,3 --search-preset high-precision src/test/resources/sergey_anatolyevich.gz test
  - if [[ ! -s test.sergey_anatolyevich.annot.txt ]]; then exit 1; fi
  - if [[ ! -s test.annot.summary.txt ]]; then exit 1; fi