language: java
sudo: required

jdk: oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

script:
  - jdk_switcher use oraclejdk8
  - gradle clean build
  - jdk_switcher use oraclejdk9
  - cd test/
  - chmod +x test.sh
  - bash test.sh