language: groovy

jdk: oraclejdk8

install:
  - git clone https://github.com/mikessh/vdjtools.git
  - cd vdjtools/
  - git checkout tags/1.1.3
  - mvn clean install -q -Dmaven.test.skip=true
  - cd ..

script:
  - gradle clean build
  - java -Xmx4G -jar `ls build/libs/vdjdb-*.jar` -v -j -S human -R TRB --search-scope 3,1,1,3 src/test/resources/sergey_anatolyevich.gz test
  - if [[ ! -s test.sergey_anatolyevich.annot.txt ]]; then echo "No results file"; exit 1; fi; rm test.sergey_anatolyevich.annot.txt
  - if [[ ! -s test.annot.summary.txt ]]; then echo "No summary file"; exit 1; fi; cat test.annot.summary.txt | head; rm test.annot.summary.txt
  - java -Xmx4G -jar `ls build/libs/vdjdb-*.jar` -v -j -S human -R TRB --search-scope 3,0,0,3 --search-scoring v1 src/test/resources/sergey_anatolyevich.gz test
  - if [[ ! -s test.sergey_anatolyevich.annot.txt ]]; then echo "No results file"; exit 1; fi
  - if [[ ! -s test.annot.summary.txt ]]; then echo "No summary file"; exit 1; fi; cat test.annot.summary.txt | head
  - java -Xmx4G -jar vdjtools/target/vdjtools-*.jar Annotate test.sergey_anatolyevich.annot.txt annot/
  - if [[ ! -s annot/metadata.txt ]]; then echo "No metadata file"; exit 1; fi
  - java -Xmx4G -jar `ls build/libs/vdjdb-*.jar` -S human -R TRB src/test/resources/empty.txt test_empty
  - if [[ ! -s test_empty.empty.annot.txt ]]; then echo "No results file"; exit 1; fi;
  - if [[ ! -s test_empty.annot.summary.txt ]]; then echo "No summary file"; exit 1; fi; cat test_empty.annot.summary.txt | head
  - java -Xmx4G -jar `ls build/libs/vdjdb-*.jar` -S human -R TRB src/test/resources/no_found.txt test_empty2
  - if [[ ! -s test_empty2.no_found.annot.txt ]]; then echo "No results file"; exit 1; fi;
  - if [[ ! -s test_empty2.annot.summary.txt ]]; then echo "No summary file"; exit 1; fi; cat test_empty2.annot.summary.txt | head