language:
  - java
  - groovy

jdk:
  - oraclejdk8

before_install:
  - git clone https://github.com/mikessh/vdjtools.git
  - cd vdjtools/
  - git checkout tags/1.0.7
  - mvn clean install -q
  - cd ..

script:
  - java -Xmx4G -jar `ls build/libs/vdjdb-*.jar` -S human -R TRB src/test/resources/sergey_anatolyevich.gz test
  - if [[ ! -s test.sergey_anatolyevich.annot.txt ]]; then exit 1; fi