language: java
sudo: required

jdk: oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install:
  - jdk_switcher use oraclejdk8

script:
  - jdk_switcher use oraclejdk8
  - gradle clean build
  - jdk_switcher use oraclejdk9
  - cd benchmark/
  - chmod +x benchmark.sh
  - bash benchmark.sh