language:
  - java
  - groovy

jdk:
  - oraclejdk8

before_install:
  - git clone https://github.com/mikessh/vdjtools.git
  - cd vdjtools/
  - git checkout tags/1.0.7
  - mvn clean install -q
  - cd ..
